name: Update Discord Status

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  push:
    branches:
      - main  # Optional: Run the workflow on push to the main branch

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Discord Status Script
        run: |
          chmod +x discord_status.sh
          ./discord_status.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add status.md
          git commit -m "Update Discord API status"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}